### ISSUE TITLE
Update check mounted files

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/file-validator#26]
In PR bioboxes/rfc#155 two new binning evaluation interfaces are introduced. Schemas of both interfaces cannot be evaluated by using the current file validator:

``` shell
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "pyinstaller/build/validate-biobox-file/out00-PYZ.pyz/validate_biobox_file.main", line 76, in run
  File "pyinstaller/build/validate-biobox-file/out00-PYZ.pyz/pymonad.Monad", line 34, in __rshift__
  File "pyinstaller/build/validate-biobox-file/out00-PYZ.pyz/pymonad.Either", line 109, in bind
  File "pyinstaller/build/validate-biobox-file/out00-PYZ.pyz/validate_biobox_file.main", line 66, in check_mounted_files
  File "pyinstaller/build/validate-biobox-file/out00-PYZ.pyz/validate_biobox_file.main", line 51, in is_file_arg
  File "pyinstaller/build/validate-biobox-file/out00-PYZ.pyz/validate_biobox_file.main", line 51, in <lambda>
```

**Comment by michaelbarton** [comment]
I looked at the PR. Is this because binning evaluation YAML is a dictionary?

**Comment by pbelmann** [comment]
Yes. I know it is not a nice solution, but we are using lists in (e.g. Assemblers) and dictionaries (e.g. Binning evaluation, read based assembler evaluation).
